# Generated by Django 6.0.4 on 2026-04-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True)),
                ('totvs_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_status', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('first_contract_end_date', models.DateField(blank=True, null=True)),
                ('second_contract_end_date', models.DateField(blank=True, null=True)),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('management_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('management_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('management_status', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='stores.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
