# Generated by Django 6.0.4 on 2026-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='management_non_transferred_records_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='management_non_transferred_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='management_records_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
