# Generated by Django 6.0.4 on 2026-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_management_non_transferred_records_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='counts_in_store_headcount',
            field=models.BooleanField(default=True),
        ),
    ]
