# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_counts_in_store_headcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="has_management_data_cached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="has_management_duplicate_cached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="has_status_divergence_cached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="has_store_divergence_cached",
            field=models.BooleanField(default=False),
        ),
    ]
