# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_derived_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="geo_cost_center_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="geo_job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
