# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_geo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="has_job_title_divergence_cached",
            field=models.BooleanField(default=False),
        ),
    ]
