# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_job_title_divergence_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="DismissalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("dismissal_date", models.DateField(blank=True, null=True)),
                ("payroll_status", models.CharField(blank=True, max_length=20, null=True)),
                ("management_status", models.CharField(blank=True, max_length=50, null=True)),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("management_store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("geo_store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("totvs_job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("management_job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("geo_job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("comparison_status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dismissal_record", to="employees.employee")),
            ],
            options={
                "ordering": ["-dismissal_date", "name"],
            },
        ),
    ]
