# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_dismissalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="dismissalrecord",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dismissalrecord",
            name="first_contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dismissalrecord",
            name="second_contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
