# Generated by Django 6.0.4 on 2026-04-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('full', 'Completa'), ('employees', 'Colaboradores'), ('stores', 'Lojas')], default='full', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('partial', 'Parcial'), ('error', 'Erro')], default='pending', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('mother_table', 'Tabela Mãe'), ('people_management', 'Gestão de Pessoas'), ('totvs', 'TOTVS')], max_length=50)),
                ('file', models.FileField(upload_to='imports/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='imports.importbatch')),
            ],
        ),
    ]
