# Generated by Django 6.0.4 on 2026-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='headcount_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='headcount_status',
            field=models.CharField(default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='management_headcount',
            field=models.IntegerField(default=0),
        ),
    ]
